// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Exchanges email/password for an access token (short-lived JWT) and an opaque refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate a user",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.CredentialsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "invalid_credentials",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile (id + email) of the user identified by the bearer access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get the authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.UserResponse"
                        }
                    },
                    "401": {
                        "description": "invalid_access_token",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Consumes the provided refresh token (revoking it) and returns a fresh access+refresh pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rotate the session tokens",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "invalid_refresh_token",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user account. Email must be unique; password must be at least 8 characters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.CredentialsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.UserResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request | weak_password | invalid_email",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "email_already_taken",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_auth_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns ok when the server is up. Does not check downstream dependencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_http.HealthResponse"
                        }
                    }
                }
            }
        },
        "/roles/adduserrole": {
            "post": {
                "description": "Adds a role to a user and returns the user's updated list of roles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Assign a role to a user",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.AddUserRoleResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles/create": {
            "post": {
                "description": "Creates a new role with the provided label. Label is normalized to lowercase and trimmed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Create a new role",
                "parameters": [
                    {
                        "description": "Role details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.CreateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.CreateRoleResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request | invalid_role_label",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "role_already_exists",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles/findbyid": {
            "get": {
                "description": "Retrieves a single role by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Get a role by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Role ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.FindByIdResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "role_not_found",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles/finduserroles": {
            "get": {
                "description": "Retrieves all roles assigned to a given user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Get the roles of a user",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.FindByUserIDResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles/removeuserrole": {
            "delete": {
                "description": "Removes a role from a user and returns the user's updated list of roles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Remove a role from a user",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.RemoveUserRoleResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/roles/searchbylabel": {
            "get": {
                "description": "Retrieves roles whose label contains the given substring.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Search roles by label",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Label search term",
                        "name": "label",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.SearchByLabelResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_roles_infra_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the API name and the build-stamped semantic version.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "API version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_http.VersionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Namularbre_knowledgeKeeperApi_internal_roles_domain.Role": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "label": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_auth_infra_http.CredentialsRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "hunter22"
                }
            }
        },
        "internal_auth_infra_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid_credentials"
                }
            }
        },
        "internal_auth_infra_http.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "vS3...opaque..."
                }
            }
        },
        "internal_auth_infra_http.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 900
                },
                "refresh_expires_in": {
                    "type": "integer",
                    "example": 604800
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "internal_auth_infra_http.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_infra_http.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_infra_http.VersionResponse": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "string",
                    "example": "knowledgeKeeperApi"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "internal_roles_infra_http.AddUserRoleResponse": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Namularbre_knowledgeKeeperApi_internal_roles_domain.Role"
                    }
                }
            }
        },
        "internal_roles_infra_http.CreateRoleRequest": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string",
                    "example": "Admin"
                }
            }
        },
        "internal_roles_infra_http.CreateRoleResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "label": {
                    "type": "string",
                    "example": "Admin"
                }
            }
        },
        "internal_roles_infra_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid_credentials"
                }
            }
        },
        "internal_roles_infra_http.FindByIdResponse": {
            "type": "object",
            "properties": {
                "role": {
                    "$ref": "#/definitions/github_com_Namularbre_knowledgeKeeperApi_internal_roles_domain.Role"
                }
            }
        },
        "internal_roles_infra_http.FindByUserIDResponse": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Namularbre_knowledgeKeeperApi_internal_roles_domain.Role"
                    }
                }
            }
        },
        "internal_roles_infra_http.RemoveUserRoleResponse": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Namularbre_knowledgeKeeperApi_internal_roles_domain.Role"
                    }
                }
            }
        },
        "internal_roles_infra_http.SearchByLabelResponse": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Namularbre_knowledgeKeeperApi_internal_roles_domain.Role"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer {token}\" where {token} is the access_token returned by /auth/login.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "knowledgeKeeperApi",
	Description:      "Personal knowledge keeper API. Auth (register/login/refresh), and metadata endpoints.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
